from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path

# ---------------------------------------------------------------------------
# Static code blocks written verbatim into the generated server.
# Rule: \\n inside these strings becomes \n in the generated file (correct
# escape inside a string literal); raw {  } are literal, no format() is used.
# ---------------------------------------------------------------------------

_IMPORTS = """\
import asyncio
import json
import os
import re

from fastmcp import FastMCP
from openai import AsyncOpenAI
"""

_HELPERS = """\
def _get_endpoint(alias):
    return BASELINE if alias == "__baseline__" else ENDPOINTS[alias]


def _parse_scores(raw, rubrics):
    def _try(text):
        try:
            d = json.loads(text)
            return d.get("scores", d) if isinstance(d, dict) else {}
        except json.JSONDecodeError:
            pass
        m = re.search(r"{.*}", text, re.DOTALL)
        if m:
            try:
                d = json.loads(m.group())
                return d.get("scores", d) if isinstance(d, dict) else {}
            except json.JSONDecodeError:
                pass
        return {}

    parsed = _try(raw)
    out = {}
    for r in rubrics:
        if r in parsed:
            try:
                out[r] = float(parsed[r])
            except (TypeError, ValueError):
                pass
    return out


async def _call(endpoint, rubrics, text):
    api_key = os.environ.get(endpoint.get("api_key_env", ""), "EMPTY") or "EMPTY"
    client = AsyncOpenAI(base_url=endpoint["base_url"], api_key=api_key)
    rubric_list = "\\n".join(f"- {r}" for r in rubrics)
    user_msg = (
        "Evaluate the following text on these criteria.\\n"
        "For each criterion provide a numeric score from 0 to 10 (floats allowed).\\n"
        'Respond ONLY with JSON: {"scores": {"Criterion": score, ...}}\\n\\n'
        f"Criteria:\\n{rubric_list}\\n\\nText:\\n{text}"
    )
    resp = await client.chat.completions.create(
        model=endpoint["model_id"],
        messages=[
            {"role": "system", "content": EVAL_PROMPT},
            {"role": "user",   "content": user_msg},
        ],
        max_tokens=endpoint.get("max_tokens", 1024),
        temperature=endpoint.get("temperature", 0.0),
    )
    return _parse_scores(resp.choices[0].message.content or "", rubrics)
"""

_TOOL = """\
@mcp.tool()
async def evaluate(text: str) -> str:
    '''Evaluate text using MOJO-routed open-weight models.'''
    groups: dict = {}
    for rubric, alias in ROUTING.items():
        groups.setdefault(alias, []).append(rubric)
    tasks = [_call(_get_endpoint(a), rs, text) for a, rs in groups.items()]
    results = await asyncio.gather(*tasks)
    scores = {}
    for (alias, rs), result in zip(groups.items(), results):
        for rubric in rs:
            scores[rubric] = result.get(rubric)
    return json.dumps({"scores": scores})


if __name__ == "__main__":
    mcp.run()
"""


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def render(config_path: str, output_path: str) -> None:
    """Generate an executable MCP server from a MOJO calibration config."""
    config = json.loads(Path(config_path).read_text())

    routing: dict[str, str] = {}
    endpoints: dict[str, dict] = {}
    for entry in config["rubric_routing"]:
        rubric = entry["rubric"]
        if entry["use_baseline"]:
            routing[rubric] = "__baseline__"
        else:
            alias = entry["best_model"]
            routing[rubric] = alias
            endpoints[alias] = entry["endpoint"]

    ts = datetime.now().isoformat(timespec="seconds")
    metric = config["metric"]
    tol = config.get("tolerance")
    server_name = config.get("server_name", "mojo-judge")

    parts = [
        f"# Auto-generated by MOJO — {ts}",
        f"# metric={metric!r}  tolerance={tol!r}",
        "",
        _IMPORTS.rstrip(),
        "",
        "",
        f"EVAL_PROMPT = {repr(config['eval_prompt'])}",
        "",
        f"ROUTING = {json.dumps(routing, indent=4)}",
        "",
        f"ENDPOINTS = {json.dumps(endpoints, indent=4)}",
        "",
        f"BASELINE = {json.dumps(config['baseline_endpoint'], indent=4)}",
        "",
        "",
        f"mcp = FastMCP({server_name!r})",
        "",
        "",
        _HELPERS.rstrip(),
        "",
        "",
        _TOOL.rstrip(),
    ]

    Path(output_path).write_text("\n".join(parts) + "\n")
    print(f"MCP server → {output_path}")
